Itransition.TeamManagement/1.Presentation/Presentation.WebUI/ViewModels/CountryViewModels/AbstractCountryViewModels/CountryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Itransition.TeamManagement.Presentation.WebUI.ViewModels.CountryViewModels.AbstractCountryViewModels
{
    public abstract class CountryViewModel
    {
        public virtual int? CountryId { get; set; }

        [Required(
            ErrorMessageResourceType = typeof(Properties.LocalResource.Country.CreateCountry),
            ErrorMessageResourceName = "CountryNameRequired")]
        [StringLength(
            25,
            MinimumLength = 2,
            ErrorMessageResourceType = typeof(Properties.LocalResource.Country.CreateCountry),
            ErrorMessageResourceName = "CountryNameStringLength")]
        public virtual string Name { get; set; }
    }
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Controllers/CountryController.cs
using System.Web.Mvc;
using Itransition.TeamManagement.Presentation.WebUI.Services.CountryServices;
using Itransition.TeamManagement.Presentation.WebUI.Services.ErrorServices;
using Itransition.TeamManagement.Presentation.WebUI.Services.Shared;
using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CountryViewModels;

namespace Itransition.TeamManagement.Presentation.WebUI.Controllers
{
    [Authorize]
    [CustomHandleError]
    public partial class CountryController : Controller
    {
        private IPresentationCountryService presentationCountryService;

        public CountryController(IPresentationCountryService presentationCountryService)
        {
            this.presentationCountryService = presentationCountryService;
        }

        [HttpGet]
        public virtual ActionResult GetCountries(int page = 1)
        {
            CountryPlaginationViewModel countryPlaginationViewModel = presentationCountryService.GetCountryPlaginationViewModel(page, Constants.PageSize);

            return View(countryPlaginationViewModel);
        }

        [HttpGet]
        public virtual ActionResult CreateCountry()
        {
            CountryCreateViewModel countryCreateViewModel = presentationCountryService.GetCountryCreateViewModel();

            return View(countryCreateViewModel);
        }

        [HttpPost]
        public virtual ActionResult CreateCountry(CountryCreateViewModel countryCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                ResultModel result = presentationCountryService.CreateCountry(countryCreateViewModel);
                if (result.IsValid)
                {
                    return RedirectToAction(MVC.Country.GetCountries());
                }
                else
                {
                    ModelState.AddModelError(nameof(countryCreateViewModel.Name), result.ErrorMessage);
                }
            }

            return View(countryCreateViewModel);
        }

        [HttpGet]
        public virtual ActionResult UpdateCountry(int? countryId)
        {
            CountryUpdateViewModel model = presentationCountryService.GetCountryUpdateViewModel(countryId);

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult UpdateCountry(CountryUpdateViewModel countryUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                ResultModel result = presentationCountryService.UpdateCountry(countryUpdateViewModel);
                if (result.IsValid)
                {
                    return RedirectToAction(MVC.Country.GetCountries());
                }
                else
                {
                    ModelState.AddModelError(nameof(countryUpdateViewModel.Name), result.ErrorMessage);
                }
            }

            return View(countryUpdateViewModel);
        }

        [HttpPost]
        public virtual ActionResult DeleteCountry(int? countryId, int page = 1)
        {
            ResultModel result = presentationCountryService.DeleteCountry(countryId);
            if (result.IsValid)
            {
                return RedirectToAction(MVC.Country.GetCountries());
            }

            return RedirectToAction(MVC.Error.Error(result.ErrorMessage));
        }
    }
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/Country/CreateCountry.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CountryViewModels
@model CountryCreateViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/SiteCss/ValidationStyles.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/CreateUserStyles.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Create User</title>
</head>
<body>
    <div class="container">
        <h2> Create new country </h2>
        <form method="post">
            @Html.ValidationSummary()
            <div class="field">
                @Html.LabelFor(m => m.Name, "Country name*")
                @Html.TextBoxFor(x => x.Name)
            </div>
            <button class="button" type="submit" style="float: right">Save</button>
        </form>
    </div>
</body>
</html>

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/Country/GetCountries.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CountryViewModels;
@using Itransition.TeamManagement.Presentation.WebUI.HtmlHelpers;
@model CountryPlaginationViewModel
@{
    int pageForDelete = Model.PageInfo.CurrentPage;

    if (pageForDelete > 1 && Model.Countries.Count == 1)
    {
        pageForDelete -= 1;
    }
}

@section Styles {
    <link href="~/Content/SiteCss/SearchWrapper.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/HomePageStyle.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/TableStyle.css" rel="stylesheet" />
}
<body>
<div class="container">
    <form method="get" action="@Url.Action("CreateCountry", "Country")">
        <button class="button" type="submit">Create country</button>
    </form>
    <div>
        <br>
        @if (Model.Countries.Count > 0)
        {
            <table class="myTable" style="text-align:center">
                <tr>
                    <th>
                        Country
                    </th>
                    <th>
                        City count
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
                @foreach (var item in Model.Countries)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.CitiesCount
                        </td>
                        <td>
                            <form method="get"><button class="button-link" type="submit" name="countryId" value="@item.CountryId" formaction="@Url.Action("UpdateCountry", "Country")">Edit</button></form>
                            <form method="post">
                                <input type="hidden" name="page" value="@pageForDelete" readonly>
                                <button class="button-link" type="submit" name="countryId" value="@item.CountryId" formaction="@Url.Action("DeleteCountry", "Country")" onclick="return check()">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </table>
            <br />
            <div class="btn-group">
                @Html.Partial("_PagesLinks", Html.PageLinks(Model.PageInfo, (x) => Url.Action("GetCountries", new { page = x })))
            </div>
        }
        else
        {
            <h2 style="text-align:center">No items. Click create</h2>
        }
    </div>
</div>
</body>
@section Scripts {
    <script src="~/Scripts/SiteJs/Check.js"></script>
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/Country/UpdateCountry.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CountryViewModels
@model CountryUpdateViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/SiteCss/ValidationStyles.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/CreateUserStyles.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Edit country</title>
</head>
<body>
    <div class="container">
        <h2> Edit country </h2>
        <form method="post">
            @Html.ValidationSummary()
            <div class="field">
                @Html.LabelFor(m => m.Name, "Country name*")
                @Html.TextBoxFor(x => x.Name)
                <input type="hidden" name="countryId" value="@Model.CountryId" readonly>
            </div>
            <button class="button" type="submit" style="float: right">Save</button>
        </form>
    </div>
</body>
</html>