Itransition.TeamManagement/1.Presentation/Presentation.WebUI/ViewModels/CityViewModels/AbstractCityViewModels/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Itransition.TeamManagement.Presentation.WebUI.ViewModels.CityViewModels.AbstractCityModels
{
    public abstract class CityViewModel
    {
        public virtual int? CityId { get; set; }

        [Required(
            ErrorMessageResourceType = typeof(Properties.LocalResource.City.CreateCity),
            ErrorMessageResourceName = "CountryRequired")]
        public virtual int? CountryId { get; set; }

        [Required(
            ErrorMessageResourceType = typeof(Properties.LocalResource.City.CreateCity),
            ErrorMessageResourceName = "CityNameRequired")]
        [StringLength(
            25,
            MinimumLength = 2,
            ErrorMessageResourceType = typeof(Properties.LocalResource.City.CreateCity),
            ErrorMessageResourceName = "CityNameStringLength")]
        public virtual string Name { get; set; }
    }
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Controllers/CityController.cs
using System.Web.Mvc;
using Itransition.TeamManagement.Presentation.WebUI.Services.CityServices;
using Itransition.TeamManagement.Presentation.WebUI.Services.ErrorServices;
using Itransition.TeamManagement.Presentation.WebUI.Services.Shared;
using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CityViewModels;

namespace Itransition.TeamManagement.Presentation.WebUI.Controllers
{
    [Authorize]
    [CustomHandleError]
    public partial class CityController : Controller
    {
        private IPresentationCityService presentationCityService;

        public CityController(IPresentationCityService presentationCityService)
        {
            this.presentationCityService = presentationCityService;
        }

        [HttpGet]
        public virtual ActionResult GetCities(int page = 1)
        {
            CityPlaginationViewModel model = presentationCityService.GetCityPlaginationViewModel(page, Constants.PageSize);

            return View(model);
        }

        [HttpGet]
        public virtual ActionResult CreateCity()
        {
            CityCreateViewModel cityCreateViewModel = presentationCityService.GetCityCreateViewModel();

            return View(cityCreateViewModel);
        }

        [HttpPost]
        public virtual ActionResult CreateCity(CityCreateViewModel cityCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                ResultModel result = presentationCityService.CreateCity(cityCreateViewModel);
                if (result.IsValid)
                {
                    return RedirectToAction(MVC.City.GetCities());
                }
                else
                {
                    ModelState.AddModelError(nameof(cityCreateViewModel.Name), result.ErrorMessage);
                }
            }

            cityCreateViewModel = presentationCityService.UpdateCityCreateViewModel(cityCreateViewModel);

            return View(cityCreateViewModel);
        }

        [HttpGet]
        public virtual ActionResult UpdateCity(int? cityId, int? countryId)
        {
            CityUpdateViewModel cityUpdateViewModel = presentationCityService.GetCityUpdateViewModel(cityId, countryId);

            return View(cityUpdateViewModel);
        }

        [HttpPost]
        public virtual ActionResult UpdateCity(CityUpdateViewModel cityUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                ResultModel result = presentationCityService.UpdateCity(cityUpdateViewModel);
                if (result.IsValid)
                {
                    return RedirectToAction(MVC.City.GetCities());
                }
                else
                {
                    ModelState.AddModelError(nameof(cityUpdateViewModel.Name), result.ErrorMessage);
                }
            }

            return View(cityUpdateViewModel);
        }

        [HttpPost]
        public virtual ActionResult DeleteCity(int? cityId, int? countryId, int page = 1)
        {
            ResultModel result = presentationCityService.DeleteCity(cityId, countryId);
            if (result.IsValid)
            {
                return RedirectToAction(MVC.City.GetCities(page));
            }

            return RedirectToAction(MVC.Error.Error(result.ErrorMessage));
        }
    }
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/City/CreateCity.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CityViewModels
@model CityCreateViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/SiteCss/ValidationStyles.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/CreateUserStyles.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Create User</title>
</head>
<body>
    <div class="container">
        <h2> Create new country </h2>
        <form method="post">
            @Html.ValidationSummary()
            <div class="field">
                @Html.LabelFor(m => m.Name, "City name*")
                @Html.TextBoxFor(x => x.Name)
            </div>
            <div class="field">
                @Html.LabelFor(m => m.CountryId, "Country*")
                @Html.DropDownListFor(x => x.CountryId, Model.Contries, "Please select value", new { id = "countryId" })
            </div>
            <input type="hidden" name="countryId" value="@Model.CountryId" readonly>
            <button class="button" type="submit" style="float: right">Save</button>
        </form>
    </div>
</body>
</html>

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/City/GetCities.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CityViewModels
@using Itransition.TeamManagement.Presentation.WebUI.HtmlHelpers;

@model CityPlaginationViewModel
@{
    int pageForDelete = Model.PageInfo.CurrentPage;

    if (pageForDelete > 1 && Model.Cities.Count == 1)
    {
        pageForDelete -= 1;
    }
}
@section Styles {
    <link href="~/Content/SiteCss/SearchWrapper.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/HomePageStyle.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/TableStyle.css" rel="stylesheet" />
}
<body>
    <div class="container">
        <form method="get" action="@Url.Action("CreateCity", "City")">
            <button class="button" type="submit">Create city</button>
        </form>
        @if (Model.Cities.Count > 0)
        {
            <div>
                <br>
                <table class="myTable">
                    <tr>
                        <th>
                            City
                        </th>
                        <th>
                            Country
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                    @foreach (var item in Model.Cities)
                    {
                        <tr>
                            <td>@item.Name </td>
                            <td>@item.CountryName</td>
                            <td>
                                <form method="get" action="@Url.Action("UpdateCity", "City")">
                                    <input type="hidden" name="countryId" value="@item.CountryId" readonly>
                                    <input type="hidden" name="cityId" value="@item.CityId" readonly>
                                    <button class="button-link" type="submit">Edit</button>
                                </form>
                                <form method="post" action="@Url.Action("DeleteCity", "City")">
                                    <input type="hidden" name="countryId" value="@item.CountryId" readonly>
                                    <input type="hidden" name="cityId" value="@item.CityId" readonly>
                                    <input type="hidden" name="page" value="@pageForDelete" readonly>
                                    <button class="button-link" type="submit" onclick="return check()">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </table>
                <br />
                <div class="btn-group">
                    @Html.Partial("_PagesLinks", Html.PageLinks(Model.PageInfo, (x) => Url.Action("GetCities", new { page = x })))
                </div>
            </div>
        }
        else
        {
            <h2 style="text-align:center">No items. Click create</h2>
        }
    </div>
</body>
@section Scripts {
    <script src="~/Scripts/SiteJs/Check.js"></script>
}

Itransition.TeamManagement/1.Presentation/Presentation.WebUI/Views/City/UpdateCity.cshtml
@using Itransition.TeamManagement.Presentation.WebUI.ViewModels.CityViewModels
@model CityUpdateViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/SiteCss/ValidationStyles.css" rel="stylesheet" />
    <link href="~/Content/SiteCss/CreateUserStyles.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Edit city</title>
</head>
<body>
    <div class="container">
        <h2> Edit city </h2>
        <form method="post">
            @Html.ValidationSummary()
            <div class="field">
                @Html.LabelFor(m => m.Name, "City name*")
                @Html.TextBoxFor(x => x.Name)
                <input type="hidden" name="countryId" value="@Model.CountryId" readonly>
                <input type="hidden" name="countryId" value="@Model.CityId" readonly>
            </div>
            <button class="button" type="submit" style="float: right">Save</button>
        </form>
    </div>
</body>
</html>